include:
  - project: rigetti/ci
    file: pipelines/docker.gitlab-ci.yml

test-python:
  stage: test
  tags:
    - github
  only:
    refs:
      - branches
  image: python:3.6
  script:
    - python --version
    - pip install -r requirements.txt
    - pytest

test-lisp:
  stage: test
  tags:
    - github
  only:
    refs:
      - branches
  image: rigetti/quicklisp
  script:
    - sbcl --version
    - make install-test-deps
    - make test
